# Generated by Django 5.0.7 on 2024-09-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='username',
        ),
    ]
