# Generated by Django 5.0.7 on 2024-09-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAdmin',
            fields=[
                ('buyer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task1.buyer')),
            ],
            bases=('task1.buyer',),
        ),
        migrations.CreateModel(
            name='GameAdmin',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task1.game')),
            ],
            bases=('task1.game',),
        ),
    ]
