# Generated by Django 5.0.7 on 2024-09-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_buyeradmin_gameadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameadmin',
            name='game_ptr',
        ),
        migrations.DeleteModel(
            name='BuyerAdmin',
        ),
        migrations.DeleteModel(
            name='GameAdmin',
        ),
    ]
